//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.CycleLogs = new HashSet<CycleLog>();
        }
    
        public int ActivityTypeId { get; set; }
        public string ActivityTypeName { get; set; }
    
        public virtual ICollection<CycleLog> CycleLogs { get; set; }
    }
}
