//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityCode
    {
        public ActivityCode()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int ActivityCodeId { get; set; }
        public string ActivityCodeName { get; set; }
        public string ActivityDesc { get; set; }
        public int ChargeTypeId { get; set; }
        public bool FSFE_Charge { get; set; }
        public bool CF_Charge { get; set; }
        public bool AF_Charge { get; set; }
        public int ActivityCodeTypeId { get; set; }
    
        public virtual ChargeType ChargeType { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ActivityCodeType ActivityCodeType { get; set; }
    }
}
