//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Activity
    {
        public int AF_ActivityId { get; set; }
        public int LotId { get; set; }
        public int AF_ActivityCodeId { get; set; }
        public int CycleId { get; set; }
        public int ConverterId { get; set; }
        public double AF_BlisterReceive_Temp { get; set; }
        public double CycleSulfer { get; set; }
        public double AF_BlisterReceive_Wt { get; set; }
        public string ActComment { get; set; }
        public bool AF_ActivityStatus { get; set; }
        public int AF_ActivityMode { get; set; }
    }
}
