//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_ActivityCode
    {
        public AF_ActivityCode()
        {
            this.AF_TimeLog = new HashSet<AF_TimeLog>();
        }
    
        public int AF_ActivityCodeId { get; set; }
        public string AF_ActivityCodeName { get; set; }
        public string AF_ActivityDesc { get; set; }
        public int AF_ActivityCodeTypeId { get; set; }
    
        public virtual AF_ActivityCodeType AF_ActivityCodeType { get; set; }
        public virtual ICollection<AF_TimeLog> AF_TimeLog { get; set; }
        public virtual AF_ActivityCode AF_ActivityCode1 { get; set; }
        public virtual AF_ActivityCode AF_ActivityCode2 { get; set; }
    }
}
