//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_AnodeReclass
    {
        public int AF_AnodeReclassId { get; set; }
        public int AF_LotId { get; set; }
        public int AF_CustomerId { get; set; }
        public int AF_GoodAnodes { get; set; }
        public int AF_ReworkableAnodes { get; set; }
        public int AF_FLL { get; set; }
        public int AF_RejectedAtPort { get; set; }
        public int AF_ReclassifiedAnodes { get; set; }
    
        public virtual AF_Customer AF_Customer { get; set; }
        public virtual AF_Lot AF_Lot { get; set; }
    }
}
