//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Activity_Timekeeping
    {
        public int AF_ActivityId { get; set; }
        public int LotId { get; set; }
        public double ActSequence { get; set; }
        public double ActDuration { get; set; }
        public System.DateTime AF_Activity_Start { get; set; }
        public System.DateTime AF_Activity_End { get; set; }
    }
}
