//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_CastingWheel
    {
        public AF_CastingWheel()
        {
            this.AF_AnodePerCustomer = new HashSet<AF_AnodePerCustomer>();
            this.AF_Customer_Val = new HashSet<AF_Customer_Val>();
            this.AF_QIG_Val = new HashSet<AF_QIG_Val>();
        }
    
        public int CastingWheelId { get; set; }
        public string CastingWheelName { get; set; }
    
        public virtual ICollection<AF_AnodePerCustomer> AF_AnodePerCustomer { get; set; }
        public virtual ICollection<AF_Customer_Val> AF_Customer_Val { get; set; }
        public virtual ICollection<AF_QIG_Val> AF_QIG_Val { get; set; }
    }
}
