//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Delay_Reason_Group
    {
        public AF_Delay_Reason_Group()
        {
            this.AF_Delay_Reason = new HashSet<AF_Delay_Reason>();
        }
    
        public int AF_DelayReasonGroupId { get; set; }
        public string DelayReasonGroup { get; set; }
    
        public virtual ICollection<AF_Delay_Reason> AF_Delay_Reason { get; set; }
    }
}
