//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Lot
    {
        public AF_Lot()
        {
            this.AF_BlisterReceive = new HashSet<AF_BlisterReceive>();
            this.AF_Param_DTime_Val = new HashSet<AF_Param_DTime_Val>();
            this.AF_Param_Emp_Val = new HashSet<AF_Param_Emp_Val>();
            this.AF_Param_Num_Val = new HashSet<AF_Param_Num_Val>();
            this.AF_QIG_Emp_Val = new HashSet<AF_QIG_Emp_Val>();
            this.AF_Param_NumMould_Val = new HashSet<AF_Param_NumMould_Val>();
            this.AF_Param_Str_Val = new HashSet<AF_Param_Str_Val>();
            this.AF_Logs_NumVal = new HashSet<AF_Logs_NumVal>();
            this.AF_Param_TimeLog = new HashSet<AF_Param_TimeLog>();
            this.AF_TimeLog = new HashSet<AF_TimeLog>();
            this.AF_AnodePerCustomer = new HashSet<AF_AnodePerCustomer>();
            this.AF_MouldInventory = new HashSet<AF_MouldInventory>();
            this.AF_Customer_Val = new HashSet<AF_Customer_Val>();
            this.AF_AnodeTransfer = new HashSet<AF_AnodeTransfer>();
            this.AF_AnodeReclass = new HashSet<AF_AnodeReclass>();
            this.AF_QIG_Weights = new HashSet<AF_QIG_Weights>();
            this.AF_QIG_Val = new HashSet<AF_QIG_Val>();
        }
    
        public int AF_LotId { get; set; }
        public int AF_NumId { get; set; }
        public int ProdYearId { get; set; }
        public int AFLotNo { get; set; }
        public int AF_StatusId { get; set; }
    
        public virtual ICollection<AF_BlisterReceive> AF_BlisterReceive { get; set; }
        public virtual AF_Num AF_Num { get; set; }
        public virtual AF_Status AF_Status { get; set; }
        public virtual ProdYear ProdYear { get; set; }
        public virtual ICollection<AF_Param_DTime_Val> AF_Param_DTime_Val { get; set; }
        public virtual ICollection<AF_Param_Emp_Val> AF_Param_Emp_Val { get; set; }
        public virtual ICollection<AF_Param_Num_Val> AF_Param_Num_Val { get; set; }
        public virtual ICollection<AF_QIG_Emp_Val> AF_QIG_Emp_Val { get; set; }
        public virtual ICollection<AF_Param_NumMould_Val> AF_Param_NumMould_Val { get; set; }
        public virtual ICollection<AF_Param_Str_Val> AF_Param_Str_Val { get; set; }
        public virtual ICollection<AF_Logs_NumVal> AF_Logs_NumVal { get; set; }
        public virtual ICollection<AF_Param_TimeLog> AF_Param_TimeLog { get; set; }
        public virtual ICollection<AF_TimeLog> AF_TimeLog { get; set; }
        public virtual ICollection<AF_AnodePerCustomer> AF_AnodePerCustomer { get; set; }
        public virtual ICollection<AF_MouldInventory> AF_MouldInventory { get; set; }
        public virtual ICollection<AF_Customer_Val> AF_Customer_Val { get; set; }
        public virtual ICollection<AF_AnodeTransfer> AF_AnodeTransfer { get; set; }
        public virtual ICollection<AF_AnodeReclass> AF_AnodeReclass { get; set; }
        public virtual ICollection<AF_QIG_Weights> AF_QIG_Weights { get; set; }
        public virtual ICollection<AF_QIG_Val> AF_QIG_Val { get; set; }
    }
}
