//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Moulds
    {
        public int AF_MouldId { get; set; }
        public string AF_MouldCode { get; set; }
        public int AF_LotId { get; set; }
        public int AF_CustomerId { get; set; }
        public string AF_Status { get; set; }
    }
}
