//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_MouldMaintenance
    {
        public int AF_MouldMaintenanceId { get; set; }
        public int AF_CastingWheel { get; set; }
        public int AF_MouldNo { get; set; }
        public System.DateTime AF_MouldReplacementTime { get; set; }
    }
}
