//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Manpower
    {
        public int AF_ManpowerId { get; set; }
        public int AF_Prod_Id { get; set; }
        public int AF_RoleTypeId { get; set; }
        public int AF_EmpId { get; set; }
        public Nullable<int> AF_AddEmpA_Id { get; set; }
        public Nullable<int> AF_AddEmpB_Id { get; set; }
        public Nullable<int> AF_LotId { get; set; }
    
        public virtual AF_Prod AF_Prod { get; set; }
    }
}
