//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Param
    {
        public AF_Param()
        {
            this.AF_Param_DTime_Val = new HashSet<AF_Param_DTime_Val>();
            this.AF_Param_Emp_Val = new HashSet<AF_Param_Emp_Val>();
            this.AF_Param_Num_Val = new HashSet<AF_Param_Num_Val>();
            this.AF_QIG_Emp_Val = new HashSet<AF_QIG_Emp_Val>();
            this.AF_Param_Num_Default_TargetVal = new HashSet<AF_Param_Num_Default_TargetVal>();
            this.AF_Param_NumMould_Val = new HashSet<AF_Param_NumMould_Val>();
            this.AF_Param_Str_Val = new HashSet<AF_Param_Str_Val>();
            this.AF_Param_Num_TargetVal = new HashSet<AF_Param_Num_TargetVal>();
            this.AF_Param_Num_Inv_Val = new HashSet<AF_Param_Num_Inv_Val>();
            this.AF_Param_Str_Inv_Val = new HashSet<AF_Param_Str_Inv_Val>();
            this.AF_Param_Emp_Inv_Val = new HashSet<AF_Param_Emp_Inv_Val>();
            this.AF_Param_Num_Inv_CurrVal = new HashSet<AF_Param_Num_Inv_CurrVal>();
            this.AF_Param_Str_Inv_CurrVal = new HashSet<AF_Param_Str_Inv_CurrVal>();
            this.AF_Param_TimeLog = new HashSet<AF_Param_TimeLog>();
            this.AF_QIG_Val = new HashSet<AF_QIG_Val>();
        }
    
        public int AF_ParamId { get; set; }
        public int AF_ParamGroup1Id { get; set; }
        public int AF_ParamGroup2Id { get; set; }
        public int AF_PageId { get; set; }
        public string AFParamName { get; set; }
        public string AFengunit { get; set; }
        public int AF_Param_TypeId { get; set; }
        public bool AFParamValid { get; set; }
    
        public virtual AF_Page AF_Page { get; set; }
        public virtual AF_Param_Type AF_Param_Type { get; set; }
        public virtual AF_ParamGroup1 AF_ParamGroup1 { get; set; }
        public virtual AF_ParamGroup2 AF_ParamGroup2 { get; set; }
        public virtual ICollection<AF_Param_DTime_Val> AF_Param_DTime_Val { get; set; }
        public virtual ICollection<AF_Param_Emp_Val> AF_Param_Emp_Val { get; set; }
        public virtual ICollection<AF_Param_Num_Val> AF_Param_Num_Val { get; set; }
        public virtual ICollection<AF_QIG_Emp_Val> AF_QIG_Emp_Val { get; set; }
        public virtual ICollection<AF_Param_Num_Default_TargetVal> AF_Param_Num_Default_TargetVal { get; set; }
        public virtual ICollection<AF_Param_NumMould_Val> AF_Param_NumMould_Val { get; set; }
        public virtual ICollection<AF_Param_Str_Val> AF_Param_Str_Val { get; set; }
        public virtual ICollection<AF_Param_Num_TargetVal> AF_Param_Num_TargetVal { get; set; }
        public virtual ICollection<AF_Param_Num_Inv_Val> AF_Param_Num_Inv_Val { get; set; }
        public virtual ICollection<AF_Param_Str_Inv_Val> AF_Param_Str_Inv_Val { get; set; }
        public virtual ICollection<AF_Param_Emp_Inv_Val> AF_Param_Emp_Inv_Val { get; set; }
        public virtual ICollection<AF_Param_Num_Inv_CurrVal> AF_Param_Num_Inv_CurrVal { get; set; }
        public virtual ICollection<AF_Param_Str_Inv_CurrVal> AF_Param_Str_Inv_CurrVal { get; set; }
        public virtual ICollection<AF_Param_TimeLog> AF_Param_TimeLog { get; set; }
        public virtual ICollection<AF_QIG_Val> AF_QIG_Val { get; set; }
    }
}
