//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Prod
    {
        public AF_Prod()
        {
            this.AF_Manpower = new HashSet<AF_Manpower>();
        }
    
        public int AF_Prod_Id { get; set; }
        public System.DateTime AF_Prod_Date { get; set; }
        public int AF_Prod_Shift { get; set; }
    
        public virtual ICollection<AF_Manpower> AF_Manpower { get; set; }
    }
}
