//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_QIG_Weights
    {
        public int AF_QIG_WeightsId { get; set; }
        public int AF_LotId { get; set; }
        public System.DateTime AF_ProductionDate { get; set; }
        public Nullable<double> AF_QIGWeight_Start { get; set; }
        public Nullable<double> AF_QIGWeight_Middle { get; set; }
        public Nullable<double> AF_QIGWeight_End { get; set; }
    
        public virtual AF_Lot AF_Lot { get; set; }
    }
}
