//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_QIGHour
    {
        public AF_QIGHour()
        {
            this.AF_QIG_Val = new HashSet<AF_QIG_Val>();
        }
    
        public int AF_QIGHourId { get; set; }
        public string AF_QIGHour1 { get; set; }
    
        public virtual ICollection<AF_QIG_Val> AF_QIG_Val { get; set; }
    }
}
