//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Shift_Assign
    {
        public int AF_Prod_Shift { get; set; }
        public System.DateTime AF_ProdDate { get; set; }
        public int AF_Shift_Id { get; set; }
    }
}
