//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_TimeLog
    {
        public int AF_TimeLogId { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<int> CastingWheelId { get; set; }
        public int AF_ActivityCodeId { get; set; }
        public System.DateTime AF_StartTimeVal { get; set; }
        public System.DateTime AF_EndTimeVal { get; set; }
        public string AF_TimeLog_Remarks { get; set; }
        public Nullable<int> AF_TabId { get; set; }
    
        public virtual AF_ActivityCode AF_ActivityCode { get; set; }
        public virtual AF_Lot AF_Lot { get; set; }
        public virtual AF_TimeLog AF_TimeLog1 { get; set; }
        public virtual AF_TimeLog AF_TimeLog2 { get; set; }
    }
}
