//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.Converters = new HashSet<Converter>();
            this.Cycles = new HashSet<Cycle>();
        }
    
        public int CampaignId { get; set; }
        public int CampaignNumber { get; set; }
    
        public virtual ICollection<Converter> Converters { get; set; }
        public virtual ICollection<Cycle> Cycles { get; set; }
    }
}
