//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangelogSilicaFormula
    {
        public int ChangelogId { get; set; }
        public int SilicaFormulaId { get; set; }
        public System.DateTime Changelogtimestamp { get; set; }
        public string Reason { get; set; }
        public int ChangebyId { get; set; }
        public int ChangeTypeId { get; set; }
    
        public virtual SilicaFormula SilicaFormula { get; set; }
    }
}
