//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Converter
    {
        public Converter()
        {
            this.Cycles = new HashSet<Cycle>();
        }
    
        public int ConverterId { get; set; }
        public string ConverterName { get; set; }
        public int CampaignId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<Cycle> Cycles { get; set; }
    }
}
