//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAssignStage
    {
        public int EmployeeAssignStageId { get; set; }
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public int EmployeeId { get; set; }
        public int EmployeeRoleStageId { get; set; }
    
        public virtual Cycle Cycle { get; set; }
        public virtual EmployeeRoleStage EmployeeRoleStage { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
