//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Energy_MG_Val
    {
        public int Energy_MG_ValId { get; set; }
        public int Energy_ParamId { get; set; }
        public System.DateTime Energy_MGDate { get; set; }
        public double Energy_MGVal { get; set; }
    
        public virtual Energy_Param Energy_Param { get; set; }
    }
}
