//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Energy_Param
    {
        public Energy_Param()
        {
            this.Energy_MG_Val = new HashSet<Energy_MG_Val>();
            this.Energy_Param_Num_Val = new HashSet<Energy_Param_Num_Val>();
        }
    
        public int Energy_ParamId { get; set; }
        public int Energy_ParamGroup1Id { get; set; }
        public string Energy_ParamName { get; set; }
        public int Energy_Param_TypeId { get; set; }
        public bool Energy_ParamValid { get; set; }
    
        public virtual ICollection<Energy_MG_Val> Energy_MG_Val { get; set; }
        public virtual Energy_ParamGroup1 Energy_ParamGroup1 { get; set; }
        public virtual ICollection<Energy_Param_Num_Val> Energy_Param_Num_Val { get; set; }
    }
}
