//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Energy_ParamGroup1
    {
        public Energy_ParamGroup1()
        {
            this.Energy_Param = new HashSet<Energy_Param>();
        }
    
        public int Energy_ParamGroup1Id { get; set; }
        public string EnergyParamGroup1Name { get; set; }
    
        public virtual ICollection<Energy_Param> Energy_Param { get; set; }
    }
}
