//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSF_Crew
    {
        public FSF_Crew()
        {
            this.FSF_AssignCrew = new HashSet<FSF_AssignCrew>();
            this.FSF_Default_Crew = new HashSet<FSF_Default_Crew>();
        }
    
        public int CrewId { get; set; }
        public string CrewName { get; set; }
    
        public virtual ICollection<FSF_AssignCrew> FSF_AssignCrew { get; set; }
        public virtual ICollection<FSF_Default_Crew> FSF_Default_Crew { get; set; }
    }
}
