//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSF_Default_Crew_List
    {
        public int FSF_DefaultCrewId { get; set; }
        public int FSF_Role_Type_Id { get; set; }
        public int FSF_CrewId { get; set; }
        public int FSF_EmpId { get; set; }
    }
}
