//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSF_Default_Crew
    {
        public int DefaultCrewId { get; set; }
        public int FSFE_Role_Type_Id { get; set; }
        public int CrewId { get; set; }
        public int EmpId { get; set; }
    
        public virtual FSF_Crew FSF_Crew { get; set; }
        public virtual FSFE_Role_Type FSFE_Role_Type { get; set; }
    }
}
