//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Buildup_Daily_Param_Val
    {
        public int FSFE_Buildup_Daily_Val_Id { get; set; }
        public int FSFE_Param_Id { get; set; }
        public System.DateTime FSFE_Date { get; set; }
        public string FSFE_Buildup_Daily_Val { get; set; }
    }
}
