//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_TimeLog
    {
        public int FSFE_TimeLogId { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public int FSFE_ActivityCodeId { get; set; }
        public System.DateTime FSFE_StartTimeVal { get; set; }
        public System.DateTime FSFE_EndTimeVal { get; set; }
        public double Duration { get; set; }
        public Nullable<double> LostTime { get; set; }
        public Nullable<double> TimeLost { get; set; }
        public Nullable<double> FeedRate { get; set; }
        public string FSFE_TimeLog_Remarks { get; set; }
    
        public virtual FSFE_ActivityCode FSFE_ActivityCode { get; set; }
    }
}
