//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Comments_Data
    {
        public int FSFE_Comment_DataId { get; set; }
        public System.DateTime FSFE_DTime { get; set; }
        public int FSFE_ParamId { get; set; }
        public string FSFE_Comment_Val { get; set; }
    }
}
