//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_SPOTap_MatteSlag
    {
        public int FSFE_MatteSlagId { get; set; }
        public int FSFE_ProdId { get; set; }
        public System.DateTime MatteSlagDate { get; set; }
        public double H1 { get; set; }
        public double H2 { get; set; }
        public double ScumLevel { get; set; }
        public double Temperature { get; set; }
        public string SPOTap_Comment { get; set; }
    
        public virtual FSFE_Prod FSFE_Prod { get; set; }
    }
}
