//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Param_Emp_Val
    {
        public int FSFE_Param_Emp_ValId { get; set; }
        public int FSFE_Param_Id { get; set; }
        public int FSFE_ProdId { get; set; }
        public int FSFE_EmpId { get; set; }
    
        public virtual FSFE_Param FSFE_Param { get; set; }
    }
}
