//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Checklist_Val
    {
        public int FSFE_Checklist_Id { get; set; }
        public int FSFE_Param_Id { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public int FSFE_ParamGroupId { get; set; }
        public bool FSFE_Boolean { get; set; }
    
        public virtual FSFE_Param FSFE_Param { get; set; }
        public virtual FSFE_ParamGroup FSFE_ParamGroup { get; set; }
        public virtual FSFE_Prod FSFE_Prod { get; set; }
    }
}
