//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Param
    {
        public FSFE_Param()
        {
            this.FSFE_Checklist_Val = new HashSet<FSFE_Checklist_Val>();
            this.FSFE_KPI_Val = new HashSet<FSFE_KPI_Val>();
            this.FSFE_Param_Val = new HashSet<FSFE_Param_Val>();
            this.FSFE_FPatternFII_Val = new HashSet<FSFE_FPatternFII_Val>();
            this.FSFE_DustlineInspection_Val = new HashSet<FSFE_DustlineInspection_Val>();
            this.FSFE_Param_Emp_Val = new HashSet<FSFE_Param_Emp_Val>();
            this.FSFE_Param_StrVal = new HashSet<FSFE_Param_StrVal>();
        }
    
        public int FSFE_Param_Id { get; set; }
        public int FSFE_Param_Type_Id { get; set; }
        public string FSFE_Param_Name { get; set; }
        public int FSFE_ParamGroupId { get; set; }
    
        public virtual ICollection<FSFE_Checklist_Val> FSFE_Checklist_Val { get; set; }
        public virtual ICollection<FSFE_KPI_Val> FSFE_KPI_Val { get; set; }
        public virtual FSFE_Param_Type FSFE_Param_Type { get; set; }
        public virtual FSFE_ParamGroup FSFE_ParamGroup { get; set; }
        public virtual ICollection<FSFE_Param_Val> FSFE_Param_Val { get; set; }
        public virtual ICollection<FSFE_FPatternFII_Val> FSFE_FPatternFII_Val { get; set; }
        public virtual ICollection<FSFE_DustlineInspection_Val> FSFE_DustlineInspection_Val { get; set; }
        public virtual ICollection<FSFE_Param_Emp_Val> FSFE_Param_Emp_Val { get; set; }
        public virtual ICollection<FSFE_Param_StrVal> FSFE_Param_StrVal { get; set; }
    }
}
