//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Param_StrVal
    {
        public int FSFE_Param_StrVal_Id { get; set; }
        public int FSFE_Param_Id { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public System.DateTime FSFE_Param_Date { get; set; }
        public string FSFE_Param_Value { get; set; }
    
        public virtual FSFE_Param FSFE_Param { get; set; }
        public virtual FSFE_Prod FSFE_Prod { get; set; }
    }
}
