//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Manpower
    {
        public int FSFE_ManpowerId { get; set; }
        public int FSFE_Shift_AssignCrewId { get; set; }
        public int FSFE_Role_Type_Id { get; set; }
        public int FSFE_EmpId { get; set; }
        public Nullable<int> FSFE_AddEmpA_Id { get; set; }
        public Nullable<int> FSFE_AddEmpB_Id { get; set; }
    }
}
