//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_KPITarget_Val
    {
        public int FSFE_KPI_TargetId { get; set; }
        public int Month { get; set; }
        public double Year { get; set; }
        public int FSFE_Param_Id { get; set; }
        public double Target { get; set; }
    }
}
