//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_ActivityCodeType
    {
        public FSFE_ActivityCodeType()
        {
            this.FSFE_ActivityCode = new HashSet<FSFE_ActivityCode>();
        }
    
        public int FSFE_ActivityCodeTypeId { get; set; }
        public string FSFE_ActivityCodeTypeName { get; set; }
    
        public virtual ICollection<FSFE_ActivityCode> FSFE_ActivityCode { get; set; }
    }
}
