//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_OnboardCrew
    {
        public int FSFE_Onboard_Crew_Id { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public int FSFE_Onboard_Employee_Id { get; set; }
        public int FSFE_Role_Type_Id { get; set; }
        public int FSFE_Onboard_AddEmpA_Id { get; set; }
        public int FSFE_Onboard_AddEmpB_Id { get; set; }
    
        public virtual FSFE_Role_Type FSFE_Role_Type { get; set; }
        public virtual FSFE_Prod FSFE_Prod { get; set; }
    }
}
