//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Role_Type
    {
        public FSFE_Role_Type()
        {
            this.FSFE_OnboardCrew = new HashSet<FSFE_OnboardCrew>();
            this.FSF_Default_Crew = new HashSet<FSF_Default_Crew>();
        }
    
        public int FSFE_Role_Type_Id { get; set; }
        public string FSFE_Role_Type_Name { get; set; }
    
        public virtual ICollection<FSFE_OnboardCrew> FSFE_OnboardCrew { get; set; }
        public virtual ICollection<FSF_Default_Crew> FSF_Default_Crew { get; set; }
    }
}
