//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_ParamGroup
    {
        public FSFE_ParamGroup()
        {
            this.FSFE_Checklist_Val = new HashSet<FSFE_Checklist_Val>();
            this.FSFE_Param1 = new HashSet<FSFE_Param>();
        }
    
        public int id { get; set; }
        public string FSFE_Param { get; set; }
    
        public virtual ICollection<FSFE_Checklist_Val> FSFE_Checklist_Val { get; set; }
        public virtual ICollection<FSFE_Param> FSFE_Param1 { get; set; }
    }
}
