//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_FII_Guideline
    {
        public int FSFE_FII_GuideId { get; set; }
        public int FSFE_ParamId { get; set; }
        public string Guideline { get; set; }
    }
}
