//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Bed
    {
        public int FSFE_Bed_Id { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public int FSFE_Bed_No { get; set; }
        public System.DateTime FSFE_Bed_StartDate { get; set; }
        public Nullable<System.DateTime> FSFE_Bed_EndDate { get; set; }
    
        public virtual FSFE_Prod FSFE_Prod { get; set; }
    }
}
