//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSFE_Target_ValueType
    {
        public int FSFE_Target_ValueTypeId { get; set; }
        public string FSFE_Target_ValueTypeDesc { get; set; }
        public string FSFE_Target_ValueType_DisplayText { get; set; }
    }
}
