//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBF_ValType
    {
        public MBF_ValType()
        {
            this.MBF_Param_Num_Val = new HashSet<MBF_Param_Num_Val>();
        }
    
        public int MBF_ValTypeId { get; set; }
        public string MBF_ValTypeName { get; set; }
    
        public virtual ICollection<MBF_Param_Num_Val> MBF_Param_Num_Val { get; set; }
    }
}
