//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBF_Param
    {
        public MBF_Param()
        {
            this.MBF_Param_Num_Val = new HashSet<MBF_Param_Num_Val>();
        }
    
        public int MBF_ParamId { get; set; }
        public int MBF_ParamGroupId { get; set; }
        public int MBF_ParamGroup2Id { get; set; }
        public int MBF_DivisionId { get; set; }
        public string MBF_ParamName { get; set; }
        public string MBF_ParamStandard { get; set; }
        public Nullable<int> MBF_ParamGroup3Id { get; set; }
    
        public virtual MBF_Division MBF_Division { get; set; }
        public virtual MBF_ParamGroup2 MBF_ParamGroup2 { get; set; }
        public virtual MBF_ParamGroup MBF_ParamGroup { get; set; }
        public virtual ICollection<MBF_Param_Num_Val> MBF_Param_Num_Val { get; set; }
        public virtual MBF_ParamGroup3 MBF_ParamGroup3 { get; set; }
    }
}
