//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DEV_KPIEntities : DbContext
    {
        public DEV_KPIEntities()
            : base("name=DEV_KPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_PI_CFCYLE_Result> SP_PI_CFCYLE(string cyclenum, Nullable<System.DateTime> udstartdate, Nullable<System.DateTime> udenddate)
        {
            var cyclenumParameter = cyclenum != null ?
                new ObjectParameter("cyclenum", cyclenum) :
                new ObjectParameter("cyclenum", typeof(string));
    
            var udstartdateParameter = udstartdate.HasValue ?
                new ObjectParameter("udstartdate", udstartdate) :
                new ObjectParameter("udstartdate", typeof(System.DateTime));
    
            var udenddateParameter = udenddate.HasValue ?
                new ObjectParameter("udenddate", udenddate) :
                new ObjectParameter("udenddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PI_CFCYLE_Result>("SP_PI_CFCYLE", cyclenumParameter, udstartdateParameter, udenddateParameter);
        }
    }
}
