//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Department
    {
        public Operation_Department()
        {
            this.SmelPlan_Param = new HashSet<SmelPlan_Param>();
        }
    
        public int Operation_Deparment_Id { get; set; }
        public string Operation_Deparment_Name { get; set; }
        public string SmelPlan_Batch_Name { get; set; }
    
        public virtual ICollection<SmelPlan_Param> SmelPlan_Param { get; set; }
    }
}
