//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_Param_Num_Val
    {
        public int PowerPlant_Param_Num_ValId { get; set; }
        public int PowerPlant_ParamId { get; set; }
        public System.DateTime PowerPlant_Date { get; set; }
        public double PowerPlant_NumVal { get; set; }
    
        public virtual PowerPlant_Param PowerPlant_Param { get; set; }
    }
}
