//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_Param
    {
        public PowerPlant_Param()
        {
            this.PowerPlant_Param_Num_Val = new HashSet<PowerPlant_Param_Num_Val>();
        }
    
        public int PowerPlant_ParamId { get; set; }
        public int PowerPlant_ParamGroupId { get; set; }
        public string PowerPlant_ParamName { get; set; }
        public string PowerPlant_ParamStandard { get; set; }
        public Nullable<int> PowerPlant_ParamReportType { get; set; }
    
        public virtual PowerPlant_ParamGroup PowerPlant_ParamGroup { get; set; }
        public virtual ICollection<PowerPlant_Param_Num_Val> PowerPlant_Param_Num_Val { get; set; }
    }
}
