//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_ParamGroup
    {
        public PowerPlant_ParamGroup()
        {
            this.PowerPlant_Param = new HashSet<PowerPlant_Param>();
        }
    
        public int PowerPlant_ParamGroupId { get; set; }
        public string PowerPlant_ParamGroupName { get; set; }
    
        public virtual ICollection<PowerPlant_Param> PowerPlant_Param { get; set; }
    }
}
