//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_ParamGroup1
    {
        public PP_ParamGroup1()
        {
            this.PP_Param = new HashSet<PP_Param>();
        }
    
        public int PP_ParamGroup1Id { get; set; }
        public string PPParamGroup1Name { get; set; }
    
        public virtual ICollection<PP_Param> PP_Param { get; set; }
    }
}
