//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_Param
    {
        public PP_Param()
        {
            this.PP_Param_Num_Val = new HashSet<PP_Param_Num_Val>();
        }
    
        public int PP_ParamId { get; set; }
        public int PP_ParamGroup1Id { get; set; }
        public string PP_ParamName { get; set; }
        public int PP_Param_TypeId { get; set; }
        public bool PP_ParamValid { get; set; }
    
        public virtual ICollection<PP_Param_Num_Val> PP_Param_Num_Val { get; set; }
        public virtual PP_ParamGroup1 PP_ParamGroup1 { get; set; }
    }
}
