//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdYear
    {
        public ProdYear()
        {
            this.AF_Lot = new HashSet<AF_Lot>();
            this.AF_Num = new HashSet<AF_Num>();
        }
    
        public int ProdYearId { get; set; }
        public int ProdYear1 { get; set; }
    
        public virtual ICollection<AF_Lot> AF_Lot { get; set; }
        public virtual ICollection<AF_Num> AF_Num { get; set; }
    }
}
