//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_ActivityCode
    {
        public int REFTH_ActivityCodeId { get; set; }
        public string REFTH_ActivityCodeName { get; set; }
        public string REFTH_ActivityDesc { get; set; }
        public int REFTH_ActivityCodeTypeId { get; set; }
    
        public virtual REFTH_ActivityCodeType REFTH_ActivityCodeType { get; set; }
        public virtual REFTH_ActivityCode REFTH_ActivityCode1 { get; set; }
        public virtual REFTH_ActivityCode REFTH_ActivityCode2 { get; set; }
    }
}
