//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_MDReasonCodes
    {
        public REFTH_MDReasonCodes()
        {
            this.REFTH_MachineDowntime = new HashSet<REFTH_MachineDowntime>();
        }
    
        public int REFTH_MDReasonId { get; set; }
        public string REFTH_MDReasonCode { get; set; }
        public string REFTH_MDReasonDesc { get; set; }
        public Nullable<int> REFTH_MachineId { get; set; }
        public Nullable<int> REFTH_ResponsibleId { get; set; }
    
        public virtual ICollection<REFTH_MachineDowntime> REFTH_MachineDowntime { get; set; }
    }
}
