//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_ParamGroup2
    {
        public REFTH_ParamGroup2()
        {
            this.REFTH_Param = new HashSet<REFTH_Param>();
        }
    
        public int REFTH_ParamGroup2Id { get; set; }
        public string REFTH_ParamGroup2Name { get; set; }
    
        public virtual ICollection<REFTH_Param> REFTH_Param { get; set; }
    }
}
