//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_PP_Actcode
    {
        public int REFTH_PPcodeId { get; set; }
        public string REFTH_ActCode { get; set; }
        public string REFTH_ActCodeDesc { get; set; }
        public string REFTH_Style_Color { get; set; }
    }
}
