//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_Default_Crew
    {
        public int REFTH_DefaultCrewId { get; set; }
        public int REFTH_RoleGroupId { get; set; }
        public int REFTH_RoleTypeId { get; set; }
        public int REFTH_CrewId { get; set; }
        public int REFTH_EmpId { get; set; }
    }
}
