//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_Manpower
    {
        public int REFTH_ManpowerId { get; set; }
        public System.DateTime REFTH_ProductionDate { get; set; }
        public int REFTH_ShiftId { get; set; }
        public int REFTH_RoleGroup_Id { get; set; }
        public int REFTH_RoleTypeId { get; set; }
        public int REFTH_EmpId { get; set; }
        public Nullable<int> REFTH_CrewId { get; set; }
    }
}
