//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_ActivityCodeType
    {
        public REFTH_ActivityCodeType()
        {
            this.REFTH_ActivityCode = new HashSet<REFTH_ActivityCode>();
        }
    
        public int REFTH_ActivityCodeTypeId { get; set; }
        public string REFTH_ActivityCodeTypeName { get; set; }
    
        public virtual ICollection<REFTH_ActivityCode> REFTH_ActivityCode { get; set; }
    }
}
