//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_Param_DTime_Val
    {
        public int REFTH_Param_DTime_ValId { get; set; }
        public int REFTH_ParamId { get; set; }
        public System.DateTime REFTH_ProductionDate { get; set; }
        public Nullable<System.DateTime> REFTH_DateTimeVal { get; set; }
    
        public virtual REFTH_Param REFTH_Param { get; set; }
    }
}
