//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_ProdPlanMonth
    {
        public int REFTH_ProdPlanMonthId { get; set; }
        public System.DateTime REFTH_ExchangeDate { get; set; }
        public int REFTH_BlockId { get; set; }
        public Nullable<int> REFTH_CropNo { get; set; }
        public Nullable<double> REFTH_NetKAH { get; set; }
        public Nullable<double> REFTH_AnodeCharged_MT { get; set; }
        public Nullable<double> REFTH_AnodeWtPc { get; set; }
        public Nullable<double> REFTH_ElapsedKAH { get; set; }
        public Nullable<double> REFTH_CurrentEff { get; set; }
        public Nullable<double> REFTH_RequiredKAH { get; set; }
        public Nullable<System.DateTime> REFTH_KAHDate { get; set; }
        public Nullable<double> REFTH_ScrapRatio { get; set; }
    }
}
