//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_Param
    {
        public REFTH_Param()
        {
            this.REFTH_Param_DTime_Val = new HashSet<REFTH_Param_DTime_Val>();
            this.REFTH_Param_Num_Val = new HashSet<REFTH_Param_Num_Val>();
        }
    
        public int REFTH_ParamId { get; set; }
        public int REFTH_ParamGroup1Id { get; set; }
        public int REFTH_ParamGroup2Id { get; set; }
        public int REFTH_PageId { get; set; }
        public string REFTHParamName { get; set; }
        public string REFTHengunit { get; set; }
        public int REFTH_Param_TypeId { get; set; }
        public bool REFTHParamValid { get; set; }
        public string REFTH_ParamDisplay { get; set; }
    
        public virtual REFTH_Page REFTH_Page { get; set; }
        public virtual ICollection<REFTH_Param_DTime_Val> REFTH_Param_DTime_Val { get; set; }
        public virtual ICollection<REFTH_Param_Num_Val> REFTH_Param_Num_Val { get; set; }
        public virtual REFTH_Param_Type REFTH_Param_Type { get; set; }
        public virtual REFTH_ParamGroup1 REFTH_ParamGroup1 { get; set; }
        public virtual REFTH_ParamGroup2 REFTH_ParamGroup2 { get; set; }
    }
}
