//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTH_PPDaily_Temp_Table_plan
    {
        public int REFTH_PId { get; set; }
        public int REFTH_PPId { get; set; }
        public int REFTH_BlockId { get; set; }
        public int REFTH_PPcodeId { get; set; }
        public string REFTH_ActCode { get; set; }
        public string REFTH_ActCodeDesc { get; set; }
        public string REFTH_Style_Color { get; set; }
        public double REFTH_ActDuration { get; set; }
        public int REFTH_ActSequence { get; set; }
        public System.DateTime REFTH_Proddate { get; set; }
        public string REFTH_Remarks { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    }
}
