//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTDUET_TARGET
    {
        public int MCId { get; set; }
        public string MCName { get; set; }
        public System.DateTime TargetStartDate { get; set; }
        public Nullable<System.DateTime> TargetEndDate { get; set; }
        public double TargetVal { get; set; }
    }
}
