//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Val_Group
    {
        public SFP_Val_Group()
        {
            this.SFP_Pots_Data = new HashSet<SFP_Pots_Data>();
        }
    
        public int SFP_Val_GroupId { get; set; }
        public string SFP_Val_GroupDesc { get; set; }
    
        public virtual ICollection<SFP_Pots_Data> SFP_Pots_Data { get; set; }
    }
}
