//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Shift
    {
        public SFP_Shift()
        {
            this.SFP_Consumable_Values = new HashSet<SFP_Consumable_Values>();
        }
    
        public int SFP_ShiftId { get; set; }
        public string SFP_ShiftDesc { get; set; }
    
        public virtual ICollection<SFP_Consumable_Values> SFP_Consumable_Values { get; set; }
    }
}
