//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_OldSFP_Values
    {
        public int SFP_OldSFP_ValId { get; set; }
        public System.DateTime SFP_Date { get; set; }
        public int WeigherId { get; set; }
        public int MaterialId { get; set; }
    }
}
