//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Consumable_Values
    {
        public int SFP_Consummable_ValId { get; set; }
        public int SFP_ShiftId { get; set; }
        public int SFP_ParamId { get; set; }
        public System.DateTime SFP_Date { get; set; }
        public Nullable<decimal> SFP_NumVal { get; set; }
    
        public virtual SFP_Param SFP_Param { get; set; }
        public virtual SFP_Shift SFP_Shift { get; set; }
    }
}
