//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Target_Values
    {
        public int SFP_Target_ValuesId { get; set; }
        public int SFP_ParamId { get; set; }
        public int SFP_Target_ValueTypeId { get; set; }
        public decimal SFP_Target_NumValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
