//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Target_ValueType
    {
        public int SFP_Target_ValueTypeId { get; set; }
        public string SFP_Target_ValueTypeDesc { get; set; }
        public string SFP_Target_ValueType_DisplayText { get; set; }
    }
}
