//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Buckets_Data
    {
        public int SFP_Bucket_DataId { get; set; }
        public System.DateTime SFP_DTime { get; set; }
        public int SFP_ParamId { get; set; }
        public Nullable<int> SFP_Bucket_Val { get; set; }
    }
}
