//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Param
    {
        public SFP_Param()
        {
            this.SFP_Consumable_Values = new HashSet<SFP_Consumable_Values>();
        }
    
        public int SFP_ParamId { get; set; }
        public int SFP_ParamGroupId { get; set; }
        public string SFP_ParamName { get; set; }
        public int SFP_Param_TypeId { get; set; }
        public bool SFP_ParamValid { get; set; }
        public string UOM { get; set; }
    
        public virtual ICollection<SFP_Consumable_Values> SFP_Consumable_Values { get; set; }
        public virtual SFP_ParamGroup1 SFP_ParamGroup1 { get; set; }
    }
}
