//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_ParamGroup1
    {
        public SFP_ParamGroup1()
        {
            this.SFP_Param = new HashSet<SFP_Param>();
        }
    
        public int SFP_ParamGroupId { get; set; }
        public string SFP_ParamGroup1Name { get; set; }
        public string SFP_ParamGroup1Type { get; set; }
    
        public virtual ICollection<SFP_Param> SFP_Param { get; set; }
    }
}
