//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Forecast_Values
    {
        public int SFP_Forecast_ValuesId { get; set; }
        public int SFP_ParamId { get; set; }
        public int SFP_TargetVal_GroupId { get; set; }
        public System.DateTime MonthYear { get; set; }
        public decimal SFP_Forecast_NumValue { get; set; }
    }
}
