//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_Shift_DPMComment_Values
    {
        public int SFP_Shift_DPMCommentId { get; set; }
        public int SFP_ParamId { get; set; }
        public System.DateTime SFP_ProdDate { get; set; }
        public int SFP_Shift_Id { get; set; }
        public string SFP_Comment_Val { get; set; }
    }
}
