//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFP_EmployeeRoleType
    {
        public int SFP_EmployeeRoleId { get; set; }
        public int SFP_EmployeeId { get; set; }
        public int SFP_RoleTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
