//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftSched
    {
        public ShiftSched()
        {
            this.TeamShifts = new HashSet<TeamShift>();
        }
    
        public int ShiftSchedId { get; set; }
        public string ShiftName { get; set; }
        public int TypeShiftId { get; set; }
    
        public virtual TypeShift TypeShift { get; set; }
        public virtual ICollection<TeamShift> TeamShifts { get; set; }
    }
}
