//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SilicaFormula
    {
        public SilicaFormula()
        {
            this.ChangelogSilicaFormulas = new HashSet<ChangelogSilicaFormula>();
            this.Cycles = new HashSet<Cycle>();
            this.DefaultSilicaFormulas = new HashSet<DefaultSilicaFormula>();
        }
    
        public int SilicaFormulaId { get; set; }
        public double IronSilicaRatio { get; set; }
    
        public virtual ICollection<ChangelogSilicaFormula> ChangelogSilicaFormulas { get; set; }
        public virtual ICollection<Cycle> Cycles { get; set; }
        public virtual ICollection<DefaultSilicaFormula> DefaultSilicaFormulas { get; set; }
    }
}
