//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SilicaFormulaVariable
    {
        public int SilicaFormulaVariableId { get; set; }
        public int ActivityId { get; set; }
        public double MatteGrade { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
