//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_TimeSeries_NumVal
    {
        public int SmelPlan_TimeSeries_ValId { get; set; }
        public int SmelPlan_Prod_Id { get; set; }
        public int SmelPlan_TimeSeries_Id { get; set; }
        public int SmelPlan_Param_Id { get; set; }
        public double SmelPlan_Numeric_Value { get; set; }
    }
}
