//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_TimeSeries
    {
        public int SmelPlan_TimeSeries_Id { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
    }
}
