//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_Default
    {
        public int SmelPlan_Default_Id { get; set; }
        public int SmelPlan_Param_Id { get; set; }
        public double SmelPlan_Default_Value { get; set; }
        public int SmelPlan_Prod_Idupto { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
    
        public virtual SmelPlan_Param SmelPlan_Param { get; set; }
    }
}
