//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_NonNumeric
    {
        public int SmelPlan_NonNumeric_Id { get; set; }
        public int SmelPlan_Prod_Id { get; set; }
        public int SmelPlan_Param_Id { get; set; }
        public string SmelPlan_NonNumeric_Value { get; set; }
    
        public virtual SmelPlan_Param SmelPlan_Param { get; set; }
        public virtual SmelPlan_Prod SmelPlan_Prod { get; set; }
    }
}
