//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_ParamType
    {
        public SmelPlan_ParamType()
        {
            this.SmelPlan_Param = new HashSet<SmelPlan_Param>();
        }
    
        public int SmelPlan_ParamType_Id { get; set; }
        public string FSFE_Param_Type_Name { get; set; }
    
        public virtual ICollection<SmelPlan_Param> SmelPlan_Param { get; set; }
    }
}
