//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_Prod
    {
        public SmelPlan_Prod()
        {
            this.SmelPlan_Batch = new HashSet<SmelPlan_Batch>();
            this.SmelPlan_Comment = new HashSet<SmelPlan_Comment>();
            this.SmelPlan_NonNumeric = new HashSet<SmelPlan_NonNumeric>();
            this.SmelPlan_Numeric = new HashSet<SmelPlan_Numeric>();
        }
    
        public int SmelPlan_Prod_Id { get; set; }
        public System.DateTime SmelPlan_Prod_date { get; set; }
    
        public virtual ICollection<SmelPlan_Batch> SmelPlan_Batch { get; set; }
        public virtual ICollection<SmelPlan_Comment> SmelPlan_Comment { get; set; }
        public virtual ICollection<SmelPlan_NonNumeric> SmelPlan_NonNumeric { get; set; }
        public virtual ICollection<SmelPlan_Numeric> SmelPlan_Numeric { get; set; }
    }
}
