//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmelPlan_Param
    {
        public SmelPlan_Param()
        {
            this.SmelPlan_Batch = new HashSet<SmelPlan_Batch>();
            this.SmelPlan_Default = new HashSet<SmelPlan_Default>();
            this.SmelPlan_NonNumeric = new HashSet<SmelPlan_NonNumeric>();
            this.SmelPlan_Numeric = new HashSet<SmelPlan_Numeric>();
        }
    
        public int SmelPlan_Param_Id { get; set; }
        public string SmelPlan_Param_Name { get; set; }
        public int SmelPlan_ParamType_Id { get; set; }
        public int Operation_Deparment_Id { get; set; }
    
        public virtual Operation_Department Operation_Department { get; set; }
        public virtual ICollection<SmelPlan_Batch> SmelPlan_Batch { get; set; }
        public virtual ICollection<SmelPlan_Default> SmelPlan_Default { get; set; }
        public virtual SmelPlan_ParamType SmelPlan_ParamType { get; set; }
        public virtual ICollection<SmelPlan_NonNumeric> SmelPlan_NonNumeric { get; set; }
        public virtual ICollection<SmelPlan_Numeric> SmelPlan_Numeric { get; set; }
    }
}
