//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.CycleStages = new HashSet<CycleStage>();
            this.Activities = new HashSet<Activity>();
            this.EmployeeAssignStages = new HashSet<EmployeeAssignStage>();
        }
    
        public int StageId { get; set; }
        public string StageName { get; set; }
        public bool StageFlag { get; set; }
    
        public virtual ICollection<CycleStage> CycleStages { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<EmployeeAssignStage> EmployeeAssignStages { get; set; }
    }
}
