//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTypeShift
    {
        public int TeamTypeShiftId { get; set; }
        public int EmployeeRoleId { get; set; }
        public System.DateTime TeamShiftDate { get; set; }
        public int TypeShiftId { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual TypeShift TypeShift { get; set; }
    }
}
