//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamShift
    {
        public int TeamShiftId { get; set; }
        public int ShiftSchedId { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public int EmployeeRoleId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual ShiftSched ShiftSched { get; set; }
    }
}
