//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SFP_Monitor_Pots
    {
        public Nullable<int> DataId { get; set; }
        public int PotNo { get; set; }
        public Nullable<int> SFP_Active { get; set; }
        public Nullable<int> SFP_GroupdId { get; set; }
    }
}
