//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_CondemnedMould_Reason
    {
        public int AF_CondemnedMould_ReasonId { get; set; }
        public string AF_CondemnedMould_Reason { get; set; }
    }
}
