//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_AnodeWeightDistribution
    {
        public int AF_AnodeWeightDistributionId { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<int> AFLotNo { get; set; }
        public int AF_CastingWheelId { get; set; }
        public string CastingWheelName { get; set; }
        public int AF_CastingTypeId { get; set; }
        public string AF_AnodeCastingType { get; set; }
        public int AF_AnodeWeightErrorId { get; set; }
        public string AF_AnodeWeightError { get; set; }
        public int AF_AnodePcs { get; set; }
    }
}
