//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_EmployeeDetail
    {
        public int AF_Param_Emp_Val { get; set; }
        public int AF_ParamId { get; set; }
        public int AF_LotId { get; set; }
        public int AF_StartEmpId { get; set; }
        public int AF_EndEmpId { get; set; }
        public string ST_Employee { get; set; }
        public string ET_Employee { get; set; }
    }
}
