//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_AnodeInventory
    {
        public int AF_AnodeInventoryId { get; set; }
        public System.DateTime AF_Inventory_Date { get; set; }
        public int AF_LocationId { get; set; }
        public string AF_LocationName { get; set; }
        public int AF_RowId { get; set; }
        public string AF_RowDesc { get; set; }
        public Nullable<int> GradeA_pcs { get; set; }
        public Nullable<int> GradeB_pcs { get; set; }
        public Nullable<int> Reworkable_pcs { get; set; }
        public Nullable<int> Reworked_pcs { get; set; }
        public Nullable<int> Reject_pcs { get; set; }
        public string Lot { get; set; }
    }
}
