//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFRefining_Str
    {
        public int AF_LotId { get; set; }
        public string SkimDelay { get; set; }
        public string OxDelay { get; set; }
        public string PollDelay { get; set; }
        public string RefiningComment { get; set; }
    }
}
