//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_DelayReasons
    {
        public int AF_DelayReasonId { get; set; }
        public string DelayReason { get; set; }
        public int AF_DelayReasonGroupId { get; set; }
        public string DelayReasonGroup { get; set; }
    }
}
