//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_LIMSTarget
    {
        public int AF_Param_Num_Default_TargetValId { get; set; }
        public int AF_ParamId { get; set; }
        public double AFTargetVal_Min { get; set; }
        public double AFTargetVal_Max { get; set; }
        public string AFDisplayTarget { get; set; }
        public string AFParamName { get; set; }
        public string AFParamGroup1Name { get; set; }
    }
}
