//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFRefining_Data
    {
        public int AF_LotId { get; set; }
        public int AF_NumId { get; set; }
        public int ProdYearId { get; set; }
        public int AFLotNo { get; set; }
        public int AF_StatusId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> ST_Skim1st { get; set; }
        public Nullable<System.DateTime> ST_Skim2nd { get; set; }
        public Nullable<System.DateTime> ST_SkimHeatup { get; set; }
        public Nullable<System.DateTime> ST_OxPartial { get; set; }
        public Nullable<System.DateTime> ST_Ox1st { get; set; }
        public Nullable<System.DateTime> ST_Ox2nd { get; set; }
        public Nullable<System.DateTime> ST_OxHeatup { get; set; }
        public Nullable<System.DateTime> ST_Poll1st { get; set; }
        public Nullable<System.DateTime> ST_Poll2nd { get; set; }
        public Nullable<System.DateTime> ST_PollHeatup { get; set; }
        public Nullable<System.DateTime> ST_Casting { get; set; }
        public Nullable<System.DateTime> ET_Skim1st { get; set; }
        public Nullable<System.DateTime> ET_Skim2nd { get; set; }
        public Nullable<System.DateTime> ET_SkimHeatup { get; set; }
        public Nullable<System.DateTime> ET_OxPartial { get; set; }
        public Nullable<System.DateTime> ET_Ox1st { get; set; }
        public Nullable<System.DateTime> ET_Ox2nd { get; set; }
        public Nullable<System.DateTime> ET_OxHeatup { get; set; }
        public Nullable<System.DateTime> ET_Poll1st { get; set; }
        public Nullable<System.DateTime> ET_Poll2nd { get; set; }
        public Nullable<System.DateTime> ET_PollHeatup { get; set; }
        public Nullable<System.DateTime> ET_Casting { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<double> TopWest { get; set; }
        public Nullable<double> TopEast { get; set; }
        public Nullable<double> BottomWest { get; set; }
        public Nullable<double> BottomEast { get; set; }
        public Nullable<double> LeadBars { get; set; }
        public Nullable<double> ScrapAnode { get; set; }
        public Nullable<double> ShortTuyere { get; set; }
        public Nullable<double> TempSkim { get; set; }
        public Nullable<double> TempOx { get; set; }
        public Nullable<double> TempPoll { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<double> SkimDelay { get; set; }
        public Nullable<double> OxDelay { get; set; }
        public Nullable<double> PollDelay { get; set; }
        public string RefiningComment { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public string ST_RSupervisor1 { get; set; }
        public string ST_CSupervisor1 { get; set; }
        public string ST_RSupervisor2 { get; set; }
        public string ST_CSupervisor2 { get; set; }
        public string ST_COperator1 { get; set; }
        public string ST_COperator2 { get; set; }
        public string ST_ROperator1 { get; set; }
        public string ST_ROperator2 { get; set; }
        public string ET_RSupervisor1 { get; set; }
        public string ET_CSupervisor1 { get; set; }
        public string ET_RSupervisor2 { get; set; }
        public string ET_CSupervisor2 { get; set; }
        public string ET_COperator1 { get; set; }
        public string ET_COperator2 { get; set; }
        public string ET_ROperator1 { get; set; }
        public string ET_ROperator2 { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public Nullable<System.DateTime> ET_Polling { get; set; }
        public Nullable<int> ST_RSupervisor1Id { get; set; }
        public Nullable<int> ST_CSupervisor1Id { get; set; }
        public Nullable<int> ST_RSupervisor2Id { get; set; }
        public Nullable<int> ST_CSupervisor2Id { get; set; }
        public Nullable<int> ST_COperator1Id { get; set; }
        public Nullable<int> ST_COperator2Id { get; set; }
        public Nullable<int> ST_ROperator1Id { get; set; }
        public Nullable<int> ST_ROperator2Id { get; set; }
        public Nullable<int> ET_RSupervisor1Id { get; set; }
        public Nullable<int> ET_CSupervisor1Id { get; set; }
        public Nullable<int> ET_RSupervisor2Id { get; set; }
        public Nullable<int> ET_CSupervisor2Id { get; set; }
        public Nullable<int> ET_COperator1Id { get; set; }
        public Nullable<int> ET_COperator2Id { get; set; }
        public Nullable<int> ET_ROperator1Id { get; set; }
        public Nullable<int> ET_ROperator2Id { get; set; }
        public Nullable<System.DateTime> ST_Blister { get; set; }
        public Nullable<double> LeadAnode { get; set; }
    }
}
