//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_QIGHrTotals
    {
        public int AF_QIG_ValId { get; set; }
        public int AF_ParamId { get; set; }
        public string AFParamName { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<int> AF_CustomerId { get; set; }
        public int AF_QIGTypeId { get; set; }
        public int AFCW { get; set; }
        public int AF_QIGHourId { get; set; }
        public Nullable<int> AnodePcs { get; set; }
        public Nullable<int> RDC { get; set; }
    }
}
