//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFQIG_DATA
    {
        public Nullable<long> RowNum { get; set; }
        public int AF_ParamId { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<System.DateTime> AF_ProductionDate { get; set; }
        public int AF_QIGTypeId { get; set; }
        public Nullable<int> CW1_1ST2ROUND { get; set; }
        public Nullable<int> CW1_1H { get; set; }
        public Nullable<int> CW1_2H { get; set; }
        public Nullable<int> CW1_3H { get; set; }
        public Nullable<int> CW1_4H { get; set; }
        public Nullable<int> CW1_5H { get; set; }
        public Nullable<int> CW1_6H { get; set; }
        public Nullable<int> CW1_7H { get; set; }
        public Nullable<int> CW1_8H { get; set; }
        public Nullable<int> CW1_9H { get; set; }
        public Nullable<int> CW1_10H { get; set; }
        public Nullable<int> CW2_1ST2ROUND { get; set; }
        public Nullable<int> CW2_1H { get; set; }
        public Nullable<int> CW2_2H { get; set; }
        public Nullable<int> CW2_3H { get; set; }
        public Nullable<int> CW2_4H { get; set; }
        public Nullable<int> CW2_5H { get; set; }
        public Nullable<int> CW2_6H { get; set; }
        public Nullable<int> CW2_7H { get; set; }
        public Nullable<int> CW2_8H { get; set; }
        public Nullable<int> CW2_9H { get; set; }
        public Nullable<int> CW2_10H { get; set; }
        public Nullable<int> CW1_OTHR_1ST2ROUND { get; set; }
        public Nullable<int> CW1_OTHR_1H { get; set; }
        public Nullable<int> CW1_OTHR_2H { get; set; }
        public Nullable<int> CW1_OTHR_3H { get; set; }
        public Nullable<int> CW1_OTHR_4H { get; set; }
        public Nullable<int> CW1_OTHR_5H { get; set; }
        public Nullable<int> CW1_OTHR_6H { get; set; }
        public Nullable<int> CW1_OTHR_7H { get; set; }
        public Nullable<int> CW1_OTHR_8H { get; set; }
        public Nullable<int> CW1_OTHR_9H { get; set; }
        public Nullable<int> CW1_OTHR_10H { get; set; }
        public Nullable<int> CW2_OTHR_1ST2ROUND { get; set; }
        public Nullable<int> CW2_OTHR_1H { get; set; }
        public Nullable<int> CW2_OTHR_2H { get; set; }
        public Nullable<int> CW2_OTHR_3H { get; set; }
        public Nullable<int> CW2_OTHR_4H { get; set; }
        public Nullable<int> CW2_OTHR_5H { get; set; }
        public Nullable<int> CW2_OTHR_6H { get; set; }
        public Nullable<int> CW2_OTHR_7H { get; set; }
        public Nullable<int> CW2_OTHR_8H { get; set; }
        public Nullable<int> CW2_OTHR_9H { get; set; }
        public Nullable<int> CW2_OTHR_10H { get; set; }
    }
}
