//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_Logs_NumVal
    {
        public int AF_TimeLogId { get; set; }
        public int AF_LotId { get; set; }
        public int LotNo { get; set; }
        public Nullable<int> ProdYear { get; set; }
        public Nullable<int> AF_ParamId { get; set; }
        public string AFParamName { get; set; }
        public Nullable<double> AF_Logs_NumVal { get; set; }
        public string NumValDesc { get; set; }
    }
}
