//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFCasting_Data
    {
        public int AF_LotId { get; set; }
        public int AF_NumId { get; set; }
        public int ProdYearId { get; set; }
        public int AFLotNo { get; set; }
        public int AF_StatusId { get; set; }
        public Nullable<System.DateTime> LotStartTime { get; set; }
        public Nullable<System.DateTime> LotEndTime { get; set; }
        public string AF_StatusName { get; set; }
        public Nullable<int> ProdYear { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<double> MM_STemp { get; set; }
        public Nullable<double> MM_MTemp { get; set; }
        public Nullable<double> MM_ETemp { get; set; }
        public Nullable<double> Mould_Dens1 { get; set; }
        public Nullable<double> Mould_Dens2 { get; set; }
        public Nullable<double> Mould_Dens3 { get; set; }
        public Nullable<double> SMould_Inv_Psr { get; set; }
        public Nullable<double> SMould_Inv_Psr_cast { get; set; }
        public Nullable<double> SMould_Inv_Crl { get; set; }
        public Nullable<double> SMould_Inv_Crl_cast { get; set; }
        public Nullable<double> Tover_Anode_pcs { get; set; }
        public Nullable<double> Tover_Anode_mt { get; set; }
        public Nullable<double> Contract_pax { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public string ST_CSupervisor1 { get; set; }
        public string ST_LOperator1 { get; set; }
        public string ST_BOperator1 { get; set; }
        public string ST_CraneOperator1 { get; set; }
        public string ST_FOperator1 { get; set; }
        public string ST_LOperator2 { get; set; }
        public string ST_BOperator2 { get; set; }
        public string ST_CraneOperator2 { get; set; }
        public string ST_FOperator2 { get; set; }
        public string ST_CSupervisor2 { get; set; }
        public string ST_COperator1 { get; set; }
        public string ST_COperator2 { get; set; }
        public Nullable<int> ST_CSupervisor1Id { get; set; }
        public Nullable<int> ST_LOperator1Id { get; set; }
        public Nullable<int> ST_BOperator1Id { get; set; }
        public Nullable<int> ST_CraneOperator1Id { get; set; }
        public Nullable<int> ST_FOperator1Id { get; set; }
        public Nullable<int> ST_LOperator2Id { get; set; }
        public Nullable<int> ST_BOperator2Id { get; set; }
        public Nullable<int> ST_CraneOperator2Id { get; set; }
        public Nullable<int> ST_FOperator2Id { get; set; }
        public Nullable<int> ST_CSupervisor2Id { get; set; }
        public Nullable<int> ST_COperator1Id { get; set; }
        public Nullable<int> ST_COperator2Id { get; set; }
        public string ET_CSupervisor1 { get; set; }
        public string ET_LOperator1 { get; set; }
        public string ET_BOperator1 { get; set; }
        public string ET_CraneOperator1 { get; set; }
        public string ET_FOperator1 { get; set; }
        public string ET_LOperator2 { get; set; }
        public string ET_BOperator2 { get; set; }
        public string ET_CraneOperator2 { get; set; }
        public string ET_FOperator2 { get; set; }
        public string ET_CSupervisor2 { get; set; }
        public string ET_COperator1 { get; set; }
        public string ET_COperator2 { get; set; }
        public Nullable<int> ET_CSupervisor1Id { get; set; }
        public Nullable<int> ET_LOperator1Id { get; set; }
        public Nullable<int> ET_BOperator1Id { get; set; }
        public Nullable<int> ET_CraneOperator1Id { get; set; }
        public Nullable<int> ET_FOperator1Id { get; set; }
        public Nullable<int> ET_LOperator2Id { get; set; }
        public Nullable<int> ET_BOperator2Id { get; set; }
        public Nullable<int> ET_CraneOperator2Id { get; set; }
        public Nullable<int> ET_FOperator2Id { get; set; }
        public Nullable<int> ET_CSupervisor2Id { get; set; }
        public Nullable<int> ET_COperator1Id { get; set; }
        public Nullable<int> ET_COperator2Id { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string CastingRemark { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<System.DateTime> CastStart { get; set; }
        public Nullable<System.DateTime> CastEnd { get; set; }
        public Nullable<System.DateTime> Cast2ndStart { get; set; }
        public Nullable<System.DateTime> Cast2ndEnd { get; set; }
        public string Wheel1_CastMould { get; set; }
        public string Wheel2_CastMould { get; set; }
        public Nullable<System.DateTime> MouldCastStart { get; set; }
        public Nullable<System.DateTime> ET_poling { get; set; }
    }
}
