//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_Refining_Delays
    {
        public int AF_ParamId { get; set; }
        public Nullable<long> DelayReasonID { get; set; }
        public int AF_LotId { get; set; }
        public string DelayReason { get; set; }
        public string AFParamName { get; set; }
    }
}
