//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_LaunderTemp
    {
        public int AF_LaunderTempId { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<int> AFLotNo { get; set; }
        public string AF_Time { get; set; }
        public double AF_Temp1 { get; set; }
        public double AF_Temp2 { get; set; }
    }
}
