//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_InspectionCategory
    {
        public int AF_ParamId { get; set; }
        public int AF_ParamGroup1Id { get; set; }
        public int AF_ParamGroup2Id { get; set; }
        public int AF_PageId { get; set; }
        public string AFParamName { get; set; }
        public string AFengunit { get; set; }
        public int AF_Param_TypeId { get; set; }
        public bool AFParamValid { get; set; }
        public string AFParamGroup1Name { get; set; }
        public string AF_ParamGroup2Name { get; set; }
        public string AFParamTypeName { get; set; }
        public string AF_PageName { get; set; }
    }
}
