//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_TimeLogs_PreCasting
    {
        public int AF_TimeLogId { get; set; }
        public int AF_LotId { get; set; }
        public int LotNo { get; set; }
        public Nullable<int> ProdYear { get; set; }
        public int AF_ActivityCodeId { get; set; }
        public string ActivityCodeName { get; set; }
        public int ActivityCodeTypeId { get; set; }
        public string ActivityDesc { get; set; }
        public string ActivityCodeTypeName { get; set; }
        public System.DateTime AF_StartTimeVal { get; set; }
        public System.DateTime AF_EndTimeVal { get; set; }
        public string AF_TimeLog_Remarks { get; set; }
        public Nullable<int> AF_TabId { get; set; }
    }
}
