//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_ActivityCode
    {
        public int AF_ActivityCodeId { get; set; }
        public string AF_ActivityCodeName { get; set; }
        public string AF_ActivityDesc { get; set; }
        public int AF_ActivityCodeTypeId { get; set; }
        public string AF_ActivityCodeTypeName { get; set; }
    }
}
