//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_Manpower
    {
        public int AF_ManpowerId { get; set; }
        public int AF_RoleTypeId { get; set; }
        public int AF_EmpId { get; set; }
        public Nullable<System.DateTime> AF_ProductionDate { get; set; }
        public Nullable<int> AF_ShiftId { get; set; }
        public Nullable<int> Emp1ID { get; set; }
        public string Emp1Name { get; set; }
        public string Emp2Name { get; set; }
        public Nullable<int> Emp2ID { get; set; }
        public string AF_RoleTypeName { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> AF_LotID { get; set; }
    }
}
