//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_AnodeCharged
    {
        public int AF_AnodeChargedId { get; set; }
        public System.DateTime AF_DTime { get; set; }
        public int AF_LotId { get; set; }
        public Nullable<int> LotNo { get; set; }
        public double AF_Weight { get; set; }
        public int AF_Pcs { get; set; }
        public string MonthYear { get; set; }
    }
}
