//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFCasting_Employee
    {
        public int AF_LotId { get; set; }
        public string ST_CSupervisor1 { get; set; }
        public string ST_LOperator1 { get; set; }
        public string ST_BOperator1 { get; set; }
        public string ST_CraneOperator1 { get; set; }
        public string ST_FOperator1 { get; set; }
        public string ST_LOperator2 { get; set; }
        public string ST_BOperator2 { get; set; }
        public string ST_CraneOperator2 { get; set; }
        public string ST_FOperator2 { get; set; }
        public string ST_CSupervisor2 { get; set; }
        public string ST_COperator1 { get; set; }
        public string ST_COperator2 { get; set; }
        public Nullable<int> ST_CSupervisor1Id { get; set; }
        public Nullable<int> ST_LOperator1Id { get; set; }
        public Nullable<int> ST_BOperator1Id { get; set; }
        public Nullable<int> ST_CraneOperator1Id { get; set; }
        public Nullable<int> ST_FOperator1Id { get; set; }
        public Nullable<int> ST_LOperator2Id { get; set; }
        public Nullable<int> ST_BOperator2Id { get; set; }
        public Nullable<int> ST_CraneOperator2Id { get; set; }
        public Nullable<int> ST_FOperator2Id { get; set; }
        public Nullable<int> ST_CSupervisor2Id { get; set; }
        public Nullable<int> ST_COperator1Id { get; set; }
        public Nullable<int> ST_COperator2Id { get; set; }
        public string ET_CSupervisor1 { get; set; }
        public string ET_LOperator1 { get; set; }
        public string ET_BOperator1 { get; set; }
        public string ET_CraneOperator1 { get; set; }
        public string ET_FOperator1 { get; set; }
        public string ET_LOperator2 { get; set; }
        public string ET_BOperator2 { get; set; }
        public string ET_CraneOperator2 { get; set; }
        public string ET_FOperator2 { get; set; }
        public string ET_CSupervisor2 { get; set; }
        public string ET_COperator1 { get; set; }
        public string ET_COperator2 { get; set; }
        public Nullable<int> ET_CSupervisor1Id { get; set; }
        public Nullable<int> ET_LOperator1Id { get; set; }
        public Nullable<int> ET_BOperator1Id { get; set; }
        public Nullable<int> ET_CraneOperator1Id { get; set; }
        public Nullable<int> ET_FOperator1Id { get; set; }
        public Nullable<int> ET_LOperator2Id { get; set; }
        public Nullable<int> ET_BOperator2Id { get; set; }
        public Nullable<int> ET_CraneOperator2Id { get; set; }
        public Nullable<int> ET_FOperator2Id { get; set; }
        public Nullable<int> ET_CSupervisor2Id { get; set; }
        public Nullable<int> ET_COperator1Id { get; set; }
        public Nullable<int> ET_COperator2Id { get; set; }
    }
}
