//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFRefining_DtTime
    {
        public int AF_LotId { get; set; }
        public Nullable<System.DateTime> ST_Skim1st { get; set; }
        public Nullable<System.DateTime> ST_Skim2nd { get; set; }
        public Nullable<System.DateTime> ST_SkimHeatup { get; set; }
        public Nullable<System.DateTime> ST_OxPartial { get; set; }
        public Nullable<System.DateTime> ST_Ox1st { get; set; }
        public Nullable<System.DateTime> ST_Ox2nd { get; set; }
        public Nullable<System.DateTime> ST_OxHeatup { get; set; }
        public Nullable<System.DateTime> ST_Poll1st { get; set; }
        public Nullable<System.DateTime> ST_Poll2nd { get; set; }
        public Nullable<System.DateTime> ST_PollHeatup { get; set; }
        public Nullable<System.DateTime> ST_Casting { get; set; }
        public Nullable<System.DateTime> ET_Skim1st { get; set; }
        public Nullable<System.DateTime> ET_Skim2nd { get; set; }
        public Nullable<System.DateTime> ET_SkimHeatup { get; set; }
        public Nullable<System.DateTime> ET_OxPartial { get; set; }
        public Nullable<System.DateTime> ET_Ox1st { get; set; }
        public Nullable<System.DateTime> ET_Ox2nd { get; set; }
        public Nullable<System.DateTime> ET_OxHeatup { get; set; }
        public Nullable<System.DateTime> ET_Poll1st { get; set; }
        public Nullable<System.DateTime> ET_Poll2nd { get; set; }
        public Nullable<System.DateTime> ET_PollHeatup { get; set; }
        public Nullable<System.DateTime> ET_Casting { get; set; }
    }
}
