//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_QIGOthers
    {
        public int AF_LotId { get; set; }
        public int AF_NumId { get; set; }
        public int ProdYearId { get; set; }
        public int AFLotNo { get; set; }
        public int AF_StatusId { get; set; }
        public Nullable<System.DateTime> LotStartTime { get; set; }
        public Nullable<System.DateTime> LotEndTime { get; set; }
        public Nullable<System.DateTime> CastStartTime { get; set; }
        public string AF_StatusName { get; set; }
        public Nullable<int> ProdYear { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CW1_CustomerId { get; set; }
        public string CW1_CustomerName { get; set; }
        public Nullable<int> CW2_CustomerId { get; set; }
        public string CW2_CustomerName { get; set; }
        public Nullable<double> RDC { get; set; }
        public Nullable<double> FLL { get; set; }
        public Nullable<int> CW1_CustomerIdOther { get; set; }
        public string CW1_CustomerNameOther { get; set; }
        public Nullable<int> CW2_CustomerIdOther { get; set; }
        public string CW2_CustomerNameOther { get; set; }
        public int CW1_Customer_AnodeTotal { get; set; }
        public int CW1_CustomerOther_AnodeTotal { get; set; }
        public int CW2_Customer_AnodeTotal { get; set; }
        public int CW2_CustomerOther_AnodeTotal { get; set; }
        public Nullable<double> CW1_CustomerTotWeight { get; set; }
        public Nullable<double> CW1_CustomerTotWeight_Othr { get; set; }
        public Nullable<double> CW2_CustomerTotWeight { get; set; }
        public Nullable<double> CW2_CustomerTotWeight_Othr { get; set; }
        public Nullable<System.DateTime> AF_ProductionDate { get; set; }
    }
}
