//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFCasting_Numeric
    {
        public int AF_LotId { get; set; }
        public Nullable<double> MM_STemp { get; set; }
        public Nullable<double> MM_MTemp { get; set; }
        public Nullable<double> MM_ETemp { get; set; }
        public Nullable<double> Mould_Dens1 { get; set; }
        public Nullable<double> Mould_Dens2 { get; set; }
        public Nullable<double> Mould_Dens3 { get; set; }
        public Nullable<double> SMould_Inv_Psr { get; set; }
        public Nullable<double> SMould_Inv_Psr_cast { get; set; }
        public Nullable<double> SMould_Inv_Crl { get; set; }
        public Nullable<double> SMould_Inv_Crl_cast { get; set; }
        public Nullable<double> Tover_Anode_pcs { get; set; }
        public Nullable<double> Tover_Anode_mt { get; set; }
        public Nullable<double> Contract_pax { get; set; }
    }
}
