//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFRefining_Employee
    {
        public int AF_LotId { get; set; }
        public string ST_RSupervisor1 { get; set; }
        public string ST_CSupervisor1 { get; set; }
        public string ST_RSupervisor2 { get; set; }
        public string ST_CSupervisor2 { get; set; }
        public string ST_COperator1 { get; set; }
        public string ST_COperator2 { get; set; }
        public string ST_ROperator1 { get; set; }
        public string ST_ROperator2 { get; set; }
        public string ET_RSupervisor1 { get; set; }
        public string ET_CSupervisor1 { get; set; }
        public string ET_RSupervisor2 { get; set; }
        public string ET_CSupervisor2 { get; set; }
        public string ET_COperator1 { get; set; }
        public string ET_COperator2 { get; set; }
        public string ET_ROperator1 { get; set; }
        public string ET_ROperator2 { get; set; }
        public Nullable<int> ST_RSupervisor1Id { get; set; }
        public Nullable<int> ST_CSupervisor1Id { get; set; }
        public Nullable<int> ST_RSupervisor2Id { get; set; }
        public Nullable<int> ST_CSupervisor2Id { get; set; }
        public Nullable<int> ST_COperator1Id { get; set; }
        public Nullable<int> ST_COperator2Id { get; set; }
        public Nullable<int> ST_ROperator1Id { get; set; }
        public Nullable<int> ST_ROperator2Id { get; set; }
        public Nullable<int> ET_RSupervisor1Id { get; set; }
        public Nullable<int> ET_CSupervisor1Id { get; set; }
        public Nullable<int> ET_RSupervisor2Id { get; set; }
        public Nullable<int> ET_CSupervisor2Id { get; set; }
        public Nullable<int> ET_COperator1Id { get; set; }
        public Nullable<int> ET_COperator2Id { get; set; }
        public Nullable<int> ET_ROperator1Id { get; set; }
        public Nullable<int> ET_ROperator2Id { get; set; }
    }
}
