//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_MaxCastingTime
    {
        public int AF_LotId { get; set; }
        public Nullable<System.DateTime> CastingEndTime { get; set; }
        public int AF_NumId { get; set; }
    }
}
