//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_QIGAnodeTotals
    {
        public int AF_LotId { get; set; }
        public Nullable<int> AF_CustomerId { get; set; }
        public Nullable<int> TotalAnodePcs { get; set; }
        public Nullable<int> RejectAnodes { get; set; }
        public Nullable<int> RDC { get; set; }
    }
}
