//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_BlisterReceive_Wt
    {
        public int AF_LotId { get; set; }
        public double AF_BlisterReceive_Wt { get; set; }
        public double SkimSlag { get; set; }
        public double AFtoAF { get; set; }
        public double BlisterNet { get; set; }
        public Nullable<long> DelayReasonID { get; set; }
    }
}
