//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAFRefining_Numeric
    {
        public int AF_LotId { get; set; }
        public Nullable<double> TopWest { get; set; }
        public Nullable<double> TopEast { get; set; }
        public Nullable<double> BottomWest { get; set; }
        public Nullable<double> BottomEast { get; set; }
        public Nullable<double> LeadBars { get; set; }
        public Nullable<double> ScrapAnode { get; set; }
        public Nullable<double> ShortTuyere { get; set; }
        public Nullable<double> TempSkim { get; set; }
        public Nullable<double> TempOx { get; set; }
        public Nullable<double> TempPoll { get; set; }
        public Nullable<double> SkimmingDelay { get; set; }
        public Nullable<double> OxidationDelay { get; set; }
        public Nullable<double> PolingDelay { get; set; }
        public Nullable<double> LeadAnode { get; set; }
    }
}
