//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_ManpowerLot
    {
        public int AF_ManpowerLotId { get; set; }
        public int AF_RoleTypeId { get; set; }
        public int AF_LotID { get; set; }
        public Nullable<int> AFLotNo { get; set; }
        public int AF_EmpId { get; set; }
        public string AF_RoleTypeName { get; set; }
        public string EmployeeName { get; set; }
    }
}
