//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAF_Lot_Targets
    {
        public int AF_Target_DefaultId { get; set; }
        public string TargetName { get; set; }
        public bool TargetType { get; set; }
        public int AF_LotId { get; set; }
        public int AFLotNo { get; set; }
        public double AFTargetVal_Min { get; set; }
        public double AFTargetVal_Max { get; set; }
        public string AFDisplayText { get; set; }
        public int AF_ParamId { get; set; }
        public string AFParamName { get; set; }
    }
}
