//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFData_All
    {
        public int CycleId { get; set; }
        public double MatteTreated { get; set; }
        public double MatteSkull { get; set; }
        public double CuSkull { get; set; }
        public double DoreReverts { get; set; }
        public double CFSlag { get; set; }
        public double BlisterProduced { get; set; }
        public double WhiteMetalCBlow { get; set; }
        public double ScattersCBlow { get; set; }
        public double CastingSlime { get; set; }
        public double AFSlag { get; set; }
        public double RejectAnode { get; set; }
        public double RejectCathodes { get; set; }
        public double CastingScrap { get; set; }
        public double CuMould { get; set; }
        public double ScrapAnode { get; set; }
        public double DepositA { get; set; }
        public double NixonFork { get; set; }
        public double MMSBlister { get; set; }
        public double MutandaScrap { get; set; }
        public double BlisterTreated { get; set; }
        public double HGS { get; set; }
        public double Katanga { get; set; }
        public double MexicanCuCement { get; set; }
        public double WhiteMetalSblow { get; set; }
        public double MatteProduced { get; set; }
        public double ScattersSblow { get; set; }
        public double MopaniReverts { get; set; }
        public double SilicaConsumption { get; set; }
        public string ConverterName { get; set; }
        public Nullable<System.DateTime> Cycle_Start_Time { get; set; }
        public Nullable<System.DateTime> Cycle_End_Time { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public double SkimSlag { get; set; }
        public Nullable<double> CuRecovery { get; set; }
        public Nullable<double> AMatteGradeSP { get; set; }
        public Nullable<double> TheoSilica { get; set; }
        public double DepAFines { get; set; }
        public double OSConcentrate { get; set; }
        public double DFcharging { get; set; }
    }
}
