//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_Supervisor
    {
        public int CycleId { get; set; }
        public Nullable<int> SupervisorStartStage { get; set; }
        public string SupervisorStart { get; set; }
        public Nullable<int> SupervisorEndStage { get; set; }
        public string SupervisorEnd { get; set; }
    }
}
