//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CuRecovery
    {
        public int CycleId { get; set; }
        public string ConverterName { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public double X1 { get; set; }
        public double X2 { get; set; }
        public double AMatteGrade { get; set; }
        public double CuRecovery { get; set; }
    }
}
