//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFData
    {
        public int CycleId { get; set; }
        public double B_AllStage { get; set; }
        public double TF { get; set; }
        public double C1_AllStage { get; set; }
        public double D { get; set; }
        public double DO { get; set; }
        public double L { get; set; }
        public double N_AllStage { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<double> A1_Cblow { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> CS { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> G1 { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> J { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> M { get; set; }
        public Nullable<double> MS { get; set; }
        public Nullable<double> MU { get; set; }
        public Nullable<double> N_Cblow { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> R { get; set; }
        public Nullable<double> S { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<double> A1_Sblow { get; set; }
        public Nullable<double> B_Sblow { get; set; }
        public Nullable<double> C_Sblow { get; set; }
        public Nullable<double> MP { get; set; }
        public Nullable<double> A { get; set; }
        public double N1 { get; set; }
        public double OSC { get; set; }
        public Nullable<double> DAF { get; set; }
        public double L1 { get; set; }
        public double DBF { get; set; }
    }
}
