//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_CuBlow
    {
        public int CycleId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<double> A1_Cblow { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> CS { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> G1 { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> J { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> M { get; set; }
        public Nullable<double> MS { get; set; }
        public Nullable<double> MU { get; set; }
        public Nullable<double> N_Cblow { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> R { get; set; }
        public Nullable<double> S { get; set; }
        public Nullable<double> D { get; set; }
        public double TC { get; set; }
        public double N_CFQty_Cblow { get; set; }
    }
}
