//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_Sequence_Data
    {
        public int CycleId { get; set; }
        public int ActivityCodeId { get; set; }
        public string ActivityDesc { get; set; }
        public string ActivityCodeName { get; set; }
        public double C1stBlow { get; set; }
        public double C2ndBlow { get; set; }
        public double C3rdBlow { get; set; }
        public double CuBlow { get; set; }
        public Nullable<int> Frequency { get; set; }
    }
}
