//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_CntrlRmEngr
    {
        public int CycleId { get; set; }
        public Nullable<int> CntrlRmEngrStartStage { get; set; }
        public string CntrlRmEngrStart { get; set; }
        public Nullable<int> CntrlRmEngrEndStage { get; set; }
        public string CntrlRmEngrEnd { get; set; }
    }
}
