//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_SlagBlow
    {
        public int CycleId { get; set; }
        public Nullable<double> B { get; set; }
        public double DO { get; set; }
        public Nullable<double> C1 { get; set; }
        public double C { get; set; }
        public double OSC { get; set; }
    }
}
