//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFData_AllStage
    {
        public int CycleId { get; set; }
        public double B_AllStage { get; set; }
        public double TF { get; set; }
        public double C1_AllStage { get; set; }
        public double D { get; set; }
        public double DO { get; set; }
        public double L { get; set; }
        public double N_AllStage { get; set; }
        public double TC { get; set; }
        public double O { get; set; }
        public double N1 { get; set; }
        public double C { get; set; }
        public double E { get; set; }
        public double A1 { get; set; }
        public double U { get; set; }
        public double Y { get; set; }
        public double CP { get; set; }
        public double OSC { get; set; }
        public double L1 { get; set; }
        public double DBF { get; set; }
    }
}
