//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_PERSTAGE_SKIMMER
    {
        public int CycleId { get; set; }
        public string C1SB_SKIMMER { get; set; }
        public string C2SB_SKIMMER { get; set; }
        public string C3SB_SKIMMER { get; set; }
        public string CUB_SKIMMER { get; set; }
    }
}
