//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFData_SlagBlow
    {
        public int CycleId { get; set; }
        public Nullable<double> A { get; set; }
        public Nullable<double> A1_Sblow { get; set; }
        public Nullable<double> B_Sblow { get; set; }
        public Nullable<double> C_Sblow { get; set; }
        public Nullable<double> MP { get; set; }
    }
}
