//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCFData_Cublow
    {
        public int CycleId { get; set; }
        public double A1_Cblow { get; set; }
        public double C { get; set; }
        public double CS { get; set; }
        public double F { get; set; }
        public double Y { get; set; }
        public double G { get; set; }
        public double G1 { get; set; }
        public double H { get; set; }
        public double I { get; set; }
        public double J { get; set; }
        public double K { get; set; }
        public double M { get; set; }
        public double MS { get; set; }
        public double MU { get; set; }
        public double N_Cblow { get; set; }
        public double P { get; set; }
        public double R { get; set; }
        public double S { get; set; }
        public double D { get; set; }
        public double DAF { get; set; }
    }
}
