//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_CVForm_Time
    {
        public int CycleId { get; set; }
        public double CycleTime { get; set; }
        public double ActivityTime { get; set; }
        public double DelayTime { get; set; }
        public double BlowingTime { get; set; }
        public double StackTime { get; set; }
    }
}
