//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCF_MatteGrade
    {
        public int FSFE_MatteGrade { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<double> MatteGrade { get; set; }
        public Nullable<long> rownum { get; set; }
    }
}
