//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCycleActiveStage
    {
        public int CycleStageId { get; set; }
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public bool ActiveStatus { get; set; }
        public string StageName { get; set; }
    }
}
