//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWEnergy_Numeric_Val
    {
        public int Energy_ParamGroup1Id { get; set; }
        public string EnergyParamGroup1Name { get; set; }
        public int Energy_ParamId { get; set; }
        public string Energy_ParamName { get; set; }
        public Nullable<double> Energy_NumVal { get; set; }
        public Nullable<bool> Energy_NumVal_Active { get; set; }
    }
}
