//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_ShiftDate
    {
        public int FSFE_Prod_Id { get; set; }
        public System.DateTime FSFE_Prod_Date { get; set; }
        public int FSFE_Prod_Shift { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.DateTime> StartShiftDate { get; set; }
        public Nullable<System.DateTime> EndShiftDate { get; set; }
    }
}
