//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_MatteTapper
    {
        public int FSFE_MatteTapperId { get; set; }
        public int FSFE_ProdId { get; set; }
        public int Tapper_Number { get; set; }
        public int Matte_Tapper_EmpId { get; set; }
        public string Fullname { get; set; }
    }
}
