//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_KPITarget
    {
        public int FSFE_Prod_Id { get; set; }
        public Nullable<int> M_T { get; set; }
        public Nullable<double> Y_T { get; set; }
        public Nullable<double> MatteTemp_T { get; set; }
        public Nullable<double> SlagTemp_T { get; set; }
        public Nullable<double> MatteGrade_T { get; set; }
        public Nullable<double> Fe_SiO2_T { get; set; }
        public Nullable<double> Matte_Skull_level_T { get; set; }
        public Nullable<double> SlagLevel_T { get; set; }
        public Nullable<double> FeedCharge_T { get; set; }
        public Nullable<double> Availability_T { get; set; }
        public Nullable<double> MatteProd_T { get; set; }
        public Nullable<double> SlagProd_T { get; set; }
        public Nullable<double> CulossSlag_T { get; set; }
    }
}
