//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_FII_Personnel
    {
        public int FSFE_Param_Emp_ValId { get; set; }
        public int FSFE_Param_Id { get; set; }
        public string FSFE_Param_Name { get; set; }
        public int FSFE_ProdId { get; set; }
        public Nullable<System.DateTime> FSFE_Prod_Date { get; set; }
        public Nullable<int> FSFE_Prod_Shift { get; set; }
        public int FSFE_EmpId { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
