//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_Buildup_Shift
    {
        public int FSFE_Buildup_Shift_Val_Id { get; set; }
        public Nullable<System.DateTime> FSFE_Prod_Date { get; set; }
        public int FSFE_Prod_Id { get; set; }
        public int FSFE_Param_Id { get; set; }
        public string FSFE_Param_Name { get; set; }
        public string FSFE_Buildup_Shift_Val { get; set; }
    }
}
