//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_Targets_Data
    {
        public int FSFE_ParamId { get; set; }
        public int FSFE_Target_ValueTypeId { get; set; }
        public decimal FSFE_Target_NumValue { get; set; }
        public string FSFE_Param_Name { get; set; }
        public Nullable<int> FSFE_ParamGroupId { get; set; }
        public string FSFE_ParamGroup { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
