//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFSFE_FPATTERN_FII
    {
        public int FSFE_FPatternFII_Id { get; set; }
        public int FSFE_ProdId { get; set; }
        public int FSFE_ParamId { get; set; }
        public string Remark { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> FSFE_ParamGroupId { get; set; }
        public string FSFE_Param_Name { get; set; }
    }
}
