//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWMatteGrade_Sequence
    {
        public Nullable<long> Sequence { get; set; }
        public int ActivityId { get; set; }
        public int ActSequence { get; set; }
        public Nullable<long> SequenceMatte { get; set; }
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public Nullable<double> MatteGrade_New { get; set; }
    }
}
