//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWMatteGrade_New
    {
        public int ActivityId { get; set; }
        public Nullable<int> CycleId { get; set; }
        public double MatteGrade_New { get; set; }
        public Nullable<long> Sequence { get; set; }
        public Nullable<int> StageId { get; set; }
        public double MatteGrade { get; set; }
    }
}
