//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWMBF_Params
    {
        public int MBF_ParamId { get; set; }
        public int MBF_ParamGroupId { get; set; }
        public int MBF_ParamGroup2Id { get; set; }
        public Nullable<int> MBF_ParamGroup3Id { get; set; }
        public int MBF_DivisionId { get; set; }
        public string MBF_DivisionName { get; set; }
        public string MBF_ParamGroupName { get; set; }
        public string MBF_ParamGroup3Name { get; set; }
        public string MBF_ParamName { get; set; }
        public string MBF_ParamStandard { get; set; }
    }
}
