//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWMBF_NumVal
    {
        public int MBF_Param_Num_ValId { get; set; }
        public int MBF_ParamId { get; set; }
        public Nullable<int> MBF_ParamGroup2Id { get; set; }
        public string MBF_ParamGroup2Name { get; set; }
        public Nullable<int> MBF_ParamGroupId { get; set; }
        public string MBF_ParamGroupName { get; set; }
        public Nullable<int> MBF_DivisionId { get; set; }
        public string MBF_DIvisionName { get; set; }
        public string MBF_ParamName { get; set; }
        public int MBF_ValTypeId { get; set; }
        public System.DateTime MBF_Date { get; set; }
        public decimal MBF_NumVal { get; set; }
        public string MonthYear { get; set; }
        public Nullable<int> MBF_ParamGroup3Id { get; set; }
        public string ParamSubgroup { get; set; }
    }
}
