//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWREFTH_MachineDowntimeResponsible
    {
        public int REFTH_MachineDowntimeRespId { get; set; }
        public Nullable<int> REFTH_MachineDowntimeId { get; set; }
        public int REFTH_ResponsibleId { get; set; }
        public string REFTH_ResponsibleDesc { get; set; }
    }
}
