//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWREF_ActiveBlocks
    {
        public int REFTH_ActiveBlocksId { get; set; }
        public int REFTH_RowId { get; set; }
        public int REF_BlockId { get; set; }
        public Nullable<int> REF_BlockNo { get; set; }
    }
}
