//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWREFTH_RoleGroup
    {
        public int REFTH_RoleGroupId { get; set; }
        public string REFTH_RoleGroupName { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Fullname { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string PositionName { get; set; }
        public string Groupname { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string EmailAddress { get; set; }
        public string ADusername { get; set; }
        public Nullable<int> REFTH_RoleTypeId { get; set; }
        public string REFTH_RoleTypeName { get; set; }
    }
}
