//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWREFTH_Shorts
    {
        public int REFTH_ShortId { get; set; }
        public System.DateTime REFTH_ProductionDate { get; set; }
        public int REFTH_ShiftId { get; set; }
        public int REFTH_PassNo { get; set; }
        public int REFTH_BlockId { get; set; }
        public Nullable<int> REFTH_BlockNo { get; set; }
        public int REFTH_RowNo { get; set; }
        public int REFTH_CellNo { get; set; }
        public int REFTH_ShortCount { get; set; }
    }
}
