//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSFP_Consumables_Data
    {
        public int SFP_Consummable_ValId { get; set; }
        public int SFP_ShiftId { get; set; }
        public string SFP_ShiftDesc { get; set; }
        public int SFP_ParamId { get; set; }
        public System.DateTime SFP_Date { get; set; }
        public Nullable<decimal> SFP_NumVal { get; set; }
        public string SFP_ParamName { get; set; }
        public int SFP_ParamGroupId { get; set; }
        public string SFP_ParamGroup1Name { get; set; }
        public string MonthYear { get; set; }
    }
}
