//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSFP_EmployeePerRole
    {
        public int SFP_EmployeeId { get; set; }
        public string FullName { get; set; }
        public int SFP_RoleTypeId { get; set; }
        public string SFP_RoleTypeName { get; set; }
    }
}
