//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSFP_Manpower
    {
        public int SFP_ManpowerId { get; set; }
        public int SFP_Role_Type_Id { get; set; }
        public int SFP_EmpId { get; set; }
        public System.DateTime SFP_ProdDate { get; set; }
        public int SFP_Shift_Id { get; set; }
        public string SFP_CrewName { get; set; }
        public int SFP_CrewId { get; set; }
        public string SFP_RoleTypeName { get; set; }
        public string EmployeeName { get; set; }
    }
}
