//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSFP_Forecast_Data
    {
        public int SFP_ParamId { get; set; }
        public decimal SFP_Forecast_NumValue { get; set; }
        public string MonthYear { get; set; }
        public string UOM { get; set; }
        public string SFP_ParamName { get; set; }
        public Nullable<int> SFP_ParamGroupId { get; set; }
        public string SFP_ParamGroup1Name { get; set; }
    }
}
