//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSFP_OldSFP_Data
    {
        public int SFP_OldSFP_ValId { get; set; }
        public int WeigherId { get; set; }
        public string WeigherName { get; set; }
        public System.DateTime SFP_Date { get; set; }
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string SFP_ParamName { get; set; }
        public Nullable<int> SFP_ParamGroupId { get; set; }
        public string SFP_ParamGroup1Name { get; set; }
        public string MonthYear { get; set; }
    }
}
