//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSPP_AdditionalKPI_Targets
    {
        public int SPP_AdditionalKPI_Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<double> KUMERASDFeed_Target_val { get; set; }
        public Nullable<double> FSFFeed_Target_val { get; set; }
        public Nullable<double> OperatingHours_Target_val { get; set; }
        public Nullable<double> BlisterProduction_Target_val { get; set; }
        public Nullable<double> CyclesCompleted_Target_val { get; set; }
        public Nullable<double> CFSecondariesCharged_Target_val { get; set; }
        public Nullable<double> AnodeCasted_Target_val { get; set; }
        public Nullable<double> LotsCompleted_Target_val { get; set; }
        public Nullable<double> KPI_MatteGrade_Target_val { get; set; }
        public decimal KPI_CuLossInSlag_Target_val { get; set; }
        public int KPI_MatteTemp_Target_val { get; set; }
        public int KPI_SlagTemp_Target_val { get; set; }
        public int KPI_BathLevelH1_Target_val { get; set; }
        public int KPI_MatteLevel_Target_val { get; set; }
        public int KPI_SlagLevel_Target_val { get; set; }
        public int KPI_FSFDraftA_Target_val { get; set; }
        public int KPI_FSFDraftB_Target_val { get; set; }
        public int KPI_WHBInletTemp_Target_val { get; set; }
        public int KPI_CUinFSSL_Target_val { get; set; }
        public int KPI_ConcFeed_Target_val { get; set; }
        public Nullable<double> KPI_CFBlowingTime_Target_val { get; set; }
        public Nullable<double> KPI_AFBlisterTreated_Target_val { get; set; }
        public int KPI_FeedToBin_Target_val { get; set; }
    }
}
