//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSPP_GraphSource
    {
        public int SPP_TimeSeriesVal_Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> TimeSeries { get; set; }
        public Nullable<decimal> Crane1 { get; set; }
        public Nullable<decimal> Crane2 { get; set; }
        public Nullable<decimal> CF1 { get; set; }
        public Nullable<decimal> CF2 { get; set; }
        public Nullable<decimal> CF3 { get; set; }
        public Nullable<decimal> CF4 { get; set; }
        public Nullable<decimal> AF1_Refining { get; set; }
        public Nullable<decimal> AF1_Casting { get; set; }
        public Nullable<decimal> AF2_Refining { get; set; }
        public Nullable<decimal> AF2_Casting { get; set; }
        public Nullable<decimal> CW1 { get; set; }
        public Nullable<decimal> CW2 { get; set; }
    }
}
