//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSPP_AdditionalKPI
    {
        public int SPP_AdditionalKPI_Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<double> KUMERASDFeed_val { get; set; }
        public Nullable<double> FSFFeed_val { get; set; }
        public Nullable<double> OperatingHours_val { get; set; }
        public Nullable<double> BlisterProduction_val { get; set; }
        public Nullable<double> CyclesCompleted_val { get; set; }
        public Nullable<double> CFSecondariesCharged_val { get; set; }
        public Nullable<double> AnodeCasted_val { get; set; }
        public Nullable<double> LotsCompleted_val { get; set; }
        public Nullable<double> KPI_MatteGrade_val { get; set; }
        public Nullable<double> KPI_CuLossInSlag_val { get; set; }
        public Nullable<double> KPI_MatteTemp_val { get; set; }
        public Nullable<double> KPI_SlagTemp_val { get; set; }
        public Nullable<double> KPI_BathLevelH1_val { get; set; }
        public Nullable<double> KPI_MatteLevel_val { get; set; }
        public Nullable<double> KPI_SlagLevel_val { get; set; }
        public Nullable<double> KPI_FSFDraftA_val { get; set; }
        public Nullable<double> KPI_FSFDraftB_val { get; set; }
        public Nullable<double> KPI_WHBInletTemp_val { get; set; }
        public Nullable<double> KPI_CUinFSSL_val { get; set; }
        public Nullable<double> KPI_ConcFeed_val { get; set; }
        public Nullable<double> KPI_CFBlowingTime_val { get; set; }
        public Nullable<double> KPI_AFBlisterTreated_val { get; set; }
        public Nullable<double> KPI_FeedToBin_val { get; set; }
    }
}
