//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSPP_DefaultValues
    {
        public int SmelPlan_Default_Id { get; set; }
        public int SmelPlan_Param_Id { get; set; }
        public string SmelPlan_Param_Name { get; set; }
        public double SmelPlan_Default_Value { get; set; }
        public int SmelPlan_Prod_Idupto { get; set; }
    }
}
