//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWTeamTypeShift
    {
        public Nullable<long> Id { get; set; }
        public Nullable<int> ShiftSchedId { get; set; }
        public int TypeShiftId { get; set; }
        public string TypeShiftName { get; set; }
        public System.DateTime TeamShiftDate { get; set; }
        public string ShiftName { get; set; }
    }
}
