//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWTuyere
    {
        public int TuyereId { get; set; }
        public int CycleId { get; set; }
        public int TuyereNumber { get; set; }
        public int TuyereStateId { get; set; }
        public string Tuyere_State { get; set; }
        public string Tuyere_State_Symbol { get; set; }
        public Nullable<int> TuyereMeasurement { get; set; }
    }
}
